### ISSUE TITLE
Remove temp images 

### ISSUE THREAD

**Issue by ckim328** [GoogleCloudPlatform/anthos-service-mesh-samples#37]
Related to this [PR](https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/235)
Found comments in yml files stating 
`# Temporarily use this container image until https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/235 is merged`

**Comment by bourgeoisor** [comment]
Looks like this will be fixed with https://github.com/GoogleCloudPlatform/anthos-service-mesh-samples/pull/39
