### ISSUE TITLE
Add detailed README for the manifests used for the ASM-ACM Tutorial

### ISSUE THREAD

**Issue by Shabirmean** [GoogleCloudPlatform/anthos-service-mesh-samples#44]
#### Description
- The current status of this repository is that, there is not much documentation exists for anyone who lands on this repo directly.
- This repo has artifacts used by docs but historically has not been kept updated with enough information
- Thus, as we move forward with adding new samples it might be useful to always accompany any new artifact with a detailed description as to what it is 
- This will be useful for the viewers of the repository and will lead to higher utility of these manifests _(since there is more than one way someone can discover and use them - docs-site + direct-repo)_

#### What needs to be added
- This issue is added to track the requirement of such documentation around the new artifacts introduced in: https://github.com/GoogleCloudPlatform/anthos-service-mesh-samples/pull/43

![image](https://user-images.githubusercontent.com/7249208/162462103-cd40c0d8-7e77-493b-92ec-92531d410ac8.png)

**Comment by ckim328** [comment]
I think this will require a few changes to the repo. As the scope of the projects/demos being hosted in this repo are larger, I've been inclined to change the directories, but I will follow up with the ASM team.
I'll update this issue with any changes that I make accordingly.
- Improve the root README.

**Comment by ckim328** [comment]
https://github.com/GoogleCloudPlatform/anthos-service-mesh-samples/issues/75 has been made in regards to the above comment
